### ISSUE TITLE
When will this be merged into Mercator?

### ISSUE THREAD

**Issue by thomasfw** [humanmade/Mercator-GUI#3]
Any estimation on when this updated GUI (and the Mercator-REST-API) will be merged into Mercator core?

I'm keen to contribute as i'd like to use Mercator in a project, but can't get any of these new feature repos or branches running without a bunch of errors.

Thanks for the awesome plugin(s) by the way :)

**Comment by rmccue** [comment]
Our policy going forward is to have a wide ecosystem of plugins, rather than keeping them in Mercator core. This is in line with our [complete software](http://engineering.hmn.md/how-we-work/philosophy/completion/) philosophy.

As to the compatibility issues, @roborourke would be best to investigate that, but he's away until the 13th, so a response may be less than timely. Hope you're enjoying your holiday season. 🎄

**Comment by roborourke** [comment]
@thomasfw as Ryan mentioned there will be a split of the functionality into a set of more focused plugins. The reason for this is that some people only need the domain mapping engine and will implement their own GUI that may include a payment step for example or other checks for valid DNS etc.

It also means it'll be easier to write tests for each component.

I'm going to tag Mercator as it is now and once I've fixed the issues in the current code reviews we'll be releasing v2

**Comment by thomasfw** [comment]
Thanks for the update and apologies for the late reply. A more pluggable and modular plugin ecosystem I can't argue with - looking forward to v2
